### Write a new message
< {%
    request.variables.set("i", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
%}
POST http://localhost:8085/facade/write-log
Content-Type: application/json

{
  "msg": "msg{{i}}"
}

### Get all messages and logs
GET http://localhost:8085/facade/logs-messages
Accept: application/json