spring:
  hazelcast:
    config: http://localhost:8500/v1/kv/config/logging-service/hazelcast?raw


---
spring:
  config:
    activate:
      on-profile: one
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: two

server:
  port: 8091

---
spring:
  config:
    activate:
      on-profile: three

server:
  port: 8092