spring:
  application:
    name: logging-service

---
spring:
  config:
    activate:
      on-profile: one
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: two

server:
  port: 8091

---
spring:
  config:
    activate:
      on-profile: three

server:
  port: 8092