spring:
  application:
    name: facade-service
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: ua.kpi.distributedsystems.message.dto

server:
  port: 8085

config-server-url: http://localhost:8888