server:
  port: 8888

config:
  urls:
    logging-service:
      - http://localhost:8090
      - http://localhost:8091
      - http://localhost:8092
    messages-service:
      - http://localhost:8088
      - http://localhost:8089
